---

- name: " Install AEM packages "
  hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}:&tag_AEMInstance_YES"
  user: ubuntu
  vars_files:
    - ../aem-variables.yml
    - ../aem-vault.yml

  tasks:

      - name: gather ec2 facts
        action: ec2_metadata_facts

      - include_tasks: ../tasks/aem_download_packages_deploy.yml
        vars_files:
          - ../aem-variables.yml
          - ../aem-vault.yml
        vars:
          deploy_s3_bucket_name: "{{ deploy_s3_bucket_name }}"
          deploy_s3_bucket_prefix: "deployments"
          Environment: "{{ Environment }}"
          Usage: "{{ Usage }}"
          Role: "{{ Role }}"
          Name: "{{ ec2_tag_Name }}"
