---

- name: " Install AEM packages "
  hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}:&tag_AEMInstance_YES"
  user: ubuntu
  vars_files:
    - ../aem-variables.yml
    - ../aem-vault.yml

  tasks:

      - name: gather ec2 facts
        action: ec2_metadata_facts

      - include_tasks: ../tasks/aem_download_packages_deploy.yml
        vars_files:
          - ../aem-variables.yml
          - ../aem-vault.yml
        vars:
          deploy_s3_bucket_name: "{{ deploy_s3_bucket_name }}"
          deploy_s3_bucket_prefix: "deployments"
          Environment: "{{ Environment }}"
          Usage: "{{ Usage }}"
          Role: "{{ Role }}"
          Name: "{{ ec2_tag_Name }}"


      - name: " Get list of all packages"
        shell:
          ls -1 {{ deploy_local_folder_packages }}/{{ ec2_tag_Environment }}/{{ ec2_tag_Usage }}/{{ ec2_tag_Name }}
        register: files
        delegate_to: localhost
      - debug: var=files.stdout_lines

      - name: " Install AEM packages "
        shell:
          curl -u '{{ aem_user_name_DevelopmentIntegrated }}:{{ aem_user_password_DevelopmentIntegrated }}' -F force=true -F install=true -F file=@"{{ deploy_local_folder_packages }}/{{ ec2_tag_Environment }}/{{ ec2_tag_Usage }}/{{ ec2_tag_Name }}/{{ item }}" http://{{ ansible_ec2_local_ipv4 }}:{{ ec2_tag_AEMPort }}/crx/packmgr/service.jsp | tail -4 | grep 'code="200"'
        delegate_to: localhost
        with_items: "{{ files.stdout_lines }}"
        register: result
      - debug: var=result.stdout_lines
