---

- hosts: localhost
  user: ubuntu
  become: true
  vars_files:
    - ../aem-variables.yml
    - ../aem-vault.yml

  tasks:

      - name: gather ec2 facts
        action: ec2_metadata_facts

      - name: " List S3 Objects "
        aws_s3:
          bucket: "dam-aem-packages-repository"
          prefix: "deployments/{{ Environment }}/{{ Usage }}/{{ Role }}"
          mode: list
          aws_access_key: "{{ deploy_read_only_aws_key }}"
          aws_secret_key: "{{ deploy_read_only_aws_secret }}"
        register: s3Objects
