---

- hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}"
  user: ubuntu
  vars_files:
    - aem-variables.yml
    - aem-vault.yml

  tasks:

      - import_playbook: aws-get-ec2-facts.yaml

      - name: Start AEM service
        shell:
          "sudo service {{aem_service_name}} start"
        register: cmdline
        become: true

      - name: Validate Quick Started is completed
        shell:
           "cat {{aem_root_dir}}/crx-quickstart/logs/startup.log | grep '{{aem_startup_complete_msg}}' "
        register: cmdline
        failed_when: "cmdline.rc != 0"
        until: cmdline.rc == 0
        retries: 15
        delay: 15

