---

- hosts: "localhost"
  user: ubuntu
  become: true
  vars_files:
    - aem-variables.yml
  tasks:

      - name: " Create temp Deploy Directory if doesn't exists "
        file:
          path: "{{ deoloy_local_folder_packages }}/{{ Environment }}/{{ Usage }}/{{ Role }}"
          state: directory
          mode: 0777
