---

- hosts: localhost
  delegate_to: localhost
  user: ubuntu
  become: true
  vars_files:
    - aem-variables.yml
  tasks:

      - name: " Create temp Deploy Directory if doesn't exists "
        file:
          path: "/tmp/temp_deploy2/packages/DevelopmentIntegrated/IDL/Author2"
          state: directory
          mode: 0777
          group: root
          owner: root
