- import_playbook: plays/stop-aem.yaml

- import_playbook: plays/start-aem.yaml

- import_playbook: plays/aem_download_packages_deploy.yaml
  vars:
    deploy_s3_bucket_prefix: "{{ deploy_s3_bucket_prefix_config_task_deploy }}"
  var_files:
    - aem-variables.yml
    - aem-vault.yml

- import_playbook: plays/aem_install_packages.yaml

- import_playbook: plays/stop-aem.yaml

- import_playbook: plays/start-aem.yaml
