---

- hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}"
  user: ubuntu
  become: true
  vars_files:
    - aem-variables.yml
  tasks:

      - name: " Create temp Deploy Directory if doesn't exists "
        file:
          path: "{{ deoloy_local_folder_packages }}"
          state: directory
          mode: 0777
          group: "{{ aem_local_group_ owner }}"
          owner: "{{ aem_local_user_ owner }}"


      - name: " Delete files inside Deploy Directory "
        file:
          path: "{{ deoloy_local_folder_packages }}"
          state: absent


      - name: " List S3 Objects "
        aws_s3:
          bucket: "{{ deploy_s3_bucket_name }}"
          prefix: "{{ deploy_s3_bucket_prefix_author }}"
          mode: list
          aws_access_key: "{{ deploy_read_only_aws_key }}"
          aws_secret_key: "{{ deploy_read_only_aws_secret }}"
        register: s3Objects


      - name: " Download S3 object to local host "
        aws_s3:
          bucket: "dam-aem-packages-repo"
          object: "{{ itme }}"
          mode: get
          dest: "{{ deoloy_local_folder_packages }}/{{ item|basename }}"
          aws_access_key: "{{ deploy_read_only_aws_key }}"
          aws_secret_key: "{{ deploy_read_only_aws_secret }}"
          overwrite: always
        with_items: "{{ s3Objects.s3_keys }}"
        when: not item|basename == "" and '.zip' in item|basename

      - name: " Debug files has been donwloaded"
        shell:
          "ls -ltr {{ deoloy_local_folder_packages }}"
        register: list_files
      -debug: var=list_files.stdout_lines
