---

- hosts: 127.0.0.1
  connection: local
  user: ubuntu
  become: true
  vars_files:
    - aem-variables.yml
  tasks:

      - name: " Create temp Deploy Directory if doesn't exists "
        file:
          path: "/tmp/temp_deploy1/packages/DevelopmentIntegrated/IDL/Author"
          state: directory
          mode: 0777
          group: root
          owner: root

