- import_playbook: plays/aem_download_packages_deploy.yaml
  vars:
    deploy_s3_bucket_prefix: "deployments"
    Environment: "{{ Environment }}"
    Usage: "{{ Usage }}"
    Role: "{{ Role }}"
    deploy_read_only_aws_key: "{{ deploy_read_only_aws_key }}"
    deploy_read_only_aws_secret: "{{ deploy_read_only_aws_secret }}"
