---

- hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}"
  user: ubuntu
  vars_files:
    - aem-variables.yml
  tasks:

      - name: Start AEM service
        shell:
          "sudo service {{aem_service_name}} start"
        register: cmdline
        become: true

      - name: Validate Quick Started is completed
        shell:
           "cat {{aem_root_dir}}/crx-quickstart/logs/startup.log | grep '{{aem_startup_complete_msg}}' "
        register: cmdline
        failed_when: "cmdline.rc != 0"
        until: cmdline.rc == 0
        retries: 15
        delay: 10

      - name: Validate all bundles are up
        uri:
          url: http://{{ ansible_ec2_instance_identity_document_privateip }}:4502/crx/packmgr/index.jsp
          status_code: "200"
          user: admin
          password: xt98m34p4kF4q$TB
        register: response
        until: response.status == 200
        retries: "4"
        delay: "5"
        delegate_to: localhost
