---

- hosts: 172.17.2.168
  user: ubuntu
  tasks:

      - name: Stop AEM service
        shell:
          sudo service aem61-publish stop
        register: cmdline
        become: true

      - name: Check process
        shell:
          ps -elf | grep java | grep 'adobe-aem6.1'
        register: cmdline
        failed_when: "cmdline.rc != 1"
        until: cmdline.rc == 1
        retries: 12
        delay: 10
